### ISSUE TITLE
Session wait iis for long time no page load

### ISSUE THREAD

**Issue by syedfahimabrar** [Rahim373/Arts.SslCommerze#1]
Trasnaction trasnaction = new Trasnaction(amount, transactionId, successUrl, failUrl,
                cancelUrl, emiTransaction, customer);
this line is making iis waiting for infinite time.

**Comment by Rahim373** [comment]
The code is working fine. There are no issues regarding transaction. Check following steps once again.

1. **sslcommerz.config** file is at the root of the project
1. **storeid** and **storepass** is valid
1. Set Copy to output directory = Copy always from sslcommerz.config file's properties
    ![image](https://user-images.githubusercontent.com/9987987/45765812-cea69380-bc57-11e8-9d4d-22ff806949df.png)
1. `Configuration.Configure();` is written at the beginning of the project.

**Comment by smfabrar** [comment]
The issue was solved by this StackOverflow thread https://stackoverflow.com/questions/53128879/async-function-in-dot-net-mvc5-controller-creating-deadlock
