### ISSUE TITLE
**কিভাবে ASP.NET MVC তে এইটা ইমপ্লিমেন্ট করবো? আমি একদম নতুন এই বিষয়ে।** 

### ISSUE THREAD

**Issue by kazirahi** [Rahim373/Arts.SslCommerze#3]
**কিভাবে ASP.NET MVC তে এইটা ইমপ্লিমেন্ট করবো? আমি একদম নতুন এই বিষয়ে।**

**Comment by Rahim373** [comment]
Check the README. There is a sample that will help you to integrate.
